export const APP_RESET_STATE = 'APP_RESET_STATE';
export const APP_SET_STATE = 'APP_SET_STATE';
export const ORDER_SET_STATE = 'ORDER_SET_STATE';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';
export const RESET_QR_DATA = 'RESET_QR_DATA';
export const ENTER_NEW_CARD = 'ENTER_NEW_CARD';
export const SET_QR_CODE_DATA = 'SET_QR_CODE_DATA';
export const SAVE_CARD_DATA = 'SAVE_CARD_DATA';
export const CHECK_IN_REQUEST = 'CHECK_IN_REQUEST';
export const ORDERS_LIST = 'ORDERS_LIST';
export const ORDER_SUMMARY = 'ORDER_SUMMARY';
export const ORDER_SET_TIPS = 'ORDER_SET_TIPS';
export const ORDER_CONFIRM = 'ORDER_CONFIRM';

export const MENU_SET_STATE = 'MENU_SET_STATE';
export const MENU_RESET_STATE = 'MENU_RESET_STATE';

export const RESERVATIONS_SET_STATE = 'RESERVATIONS_SET_STATE';
export const RESERVATIONS_RESET_STATE = 'RESERVATIONS_RESET_STATE';

export const TRANSACTIONS_SET_STATE = 'TRANSACTIONS_SET_STATE';
export const TRANSACTIONS_RESET_STATE = 'TRANSACTIONS_RESET_STATE';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';

export const SET_CART = 'SET_CART';
